# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZNAudioRecord' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZNAudioRecord

  pod 'AFNetworking'

  target 'ZNAudioRecordTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZNAudioRecordUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
